title: IDAM.CORE
tagline: Identity & Cloud Security Practitioner
url: https://pankajparmaar.github.io
baseurl: "/iam-threat-model"
lang: en-US
timezone: Asia/Kolkata
avatar: https://github.com/pankajparmaar.png
social:
  name: Pankaj Parmar
  email: pankaj@example.com
  links:
    - https://github.com/pankajparmaar
